# Docker Compose para CORE Capture SaaS
# Nota: Este projeto usa Supabase como backend, então não há backend Node.js separado
# O Supabase gerencia: banco de dados, autenticação, storage e edge functions

version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - app-network

  # Nginx Reverse Proxy (para suporte a domínios customizados)
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./ssl-certs:/etc/nginx/ssl
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Para configurar:
# 1. Configure as variáveis no .env baseado no .env.example
# 2. Configure Supabase (já configurado no projeto)
# 3. Execute: docker-compose up -d
# 4. Para domínios customizados, configure o nginx-proxy.conf