// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlhtubjjznbzxwsvzjqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaHR1Ympqem5ienh3c3Z6anF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzAzNDMsImV4cCI6MjA3NDIwNjM0M30.dKhXLN_b1vRdhp0Pxx9PbXFZ6SFX8HeXDEioHsHLoLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});